const express = require("express");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

const products = [
  {
    "id": 1,
    "title": "Levi's Men's Slim Fit Denim Jeans",
    "brand": "Levi's",
    "category": "men",
    "price": 3499,
    "discountPercentage": 20,
    "discountedPrice": 2799,
    "stock": 40,
    "rating": 4.4,
    "description": "Premium slim fit stretchable denim jeans designed for modern men with all-day comfort and durability.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/jean/j/e/d/-original-imah2mvtsxdvmthe.jpeg?q=70"
  },
  {
    "id": 2,
    "title": "Nike Men's Dri-FIT Sports T-Shirt",
    "brand": "Nike",
    "category": "men",
    "price": 1999,
    "discountPercentage": 25,
    "discountedPrice": 1499,
    "stock": 55,
    "rating": 4.5,
    "description": "Breathable and sweat-wicking Dri-FIT t-shirt perfect for gym, running, and daily active wear.",
    "img": "https://rukminim2.flixcart.com/img/612/612/kzllrbk0/t-shirt/o/m/y/m-cz9185-013-nike-original-imagbks5csvtjxuu.jpeg?q=70"
  },
  {
    "id": 3,
    "title": "Zara Women's Floral Summer Dress",
    "brand": "Zara",
    "category": "women",
    "price": 3999,
    "discountPercentage": 30,
    "discountedPrice": 2799,
    "stock": 30,
    "rating": 4.6,
    "description": "Elegant floral printed summer dress made from lightweight fabric, ideal for outings and parties.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/dress/u/o/1/xxl-pltazdr86plum-azzurra-original-imahg3zxxzeetywk.jpeg?q=70"
  },
  {
    "id": 4,
    "title": "H&M Women's Casual Cotton Top",
    "brand": "H&M",
    "category": "women",
    "price": 1499,
    "discountPercentage": 18,
    "discountedPrice": 1229,
    "stock": 65,
    "rating": 4.3,
    "description": "Soft cotton casual top with comfortable fit and trendy design for everyday wear.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/kurta/t/o/7/s-blue-kurti-print-darzi-fashion-kendra-original-imahjx3qzy7thgmx.jpeg?q=70"
  },
  {
    "id": 5,
    "title": "US Polo Kids Printed T-Shirt",
    "brand": "US Polo",
    "category": "kids",
    "price": 999,
    "discountPercentage": 15,
    "discountedPrice": 849,
    "stock": 70,
    "rating": 4.2,
    "description": "Comfortable and stylish printed t-shirt for kids made with soft breathable cotton fabric.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/kids-t-shirt/t/c/3/4-5-years-uktsh1450-u-s-polo-assn-original-imah5txfa5yxvr6a.jpeg?q=70"
  },




  {
    "id": 6,
    "title": "Adidas Men's Regular Fit Hoodie",
    "brand": "Adidas",
    "category": "men",
    "price": 4599,
    "discountPercentage": 18,
    "discountedPrice": 3771,
    "stock": 35,
    "rating": 4.4,
    "description": "Comfortable cotton blend hoodie with adjustable hood and front kangaroo pocket for casual and winter wear.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/sweatshirt/z/k/s/m-iw2939-adidas-original-imah4ya2r9hwezhb.jpeg?q=70"
  },
  {
    "id": 7,
    "title": "Puma Women's High Waist Leggings",
    "brand": "Puma",
    "category": "women",
    "price": 2499,
    "discountPercentage": 22,
    "discountedPrice": 1949,
    "stock": 48,
    "rating": 4.5,
    "description": "Stretchable and breathable high waist leggings designed for yoga, gym, and casual wear.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/tight/6/x/q/l-52752001-puma-original-imahezpshk5z3yh7.jpeg?q=70"
  },
  {
    "id": 8,
    "title": "Allen Solly Men's Formal Shirt",
    "brand": "Allen Solly",
    "category": "men",
    "price": 2799,
    "discountPercentage": 20,
    "discountedPrice": 2239,
    "stock": 42,
    "rating": 4.3,
    "description": "Premium cotton formal shirt with slim fit design, perfect for office and business meetings.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/shirt/r/5/9/46-assfmmoph09842-allen-solly-original-imahekxpdh4rkbjs.jpeg?q=70"
  },
  {
    "id": 9,
    "title": "Zara Kids Denim Jacket",
    "brand": "Zara",
    "category": "kids",
    "price": 2999,
    "discountPercentage": 25,
    "discountedPrice": 2249,
    "stock": 26,
    "rating": 4.6,
    "description": "Stylish denim jacket for kids made with durable fabric and comfortable inner lining.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/jacket/0/r/h/6-7-years-1-no-denim-jakert-black-fashiva-original-imahgxszfkqmj3v4.jpeg?q=70"
  },
  {
    "id": 10,
    "title": "H&M Women's Oversized Sweatshirt",
    "brand": "H&M",
    "category": "women",
    "price": 2199,
    "discountPercentage": 19,
    "discountedPrice": 1781,
    "stock": 50,
    "rating": 4.4,
    "description": "Trendy oversized sweatshirt made with soft fleece fabric for cozy and relaxed styling.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/sweatshirt/k/a/h/m-tbt-sw-strip-knot-brown-tabadtod-original-imahftfhgahtgz8t.jpeg?q=70"
  },




  {
    "id": 11,
    "title": "Roadster Men's Casual Check Shirt",
    "brand": "Roadster",
    "category": "men",
    "price": 1899,
    "discountPercentage": 21,
    "discountedPrice": 1500,
    "stock": 46,
    "rating": 4.2,
    "description": "Trendy casual check shirt made with breathable cotton fabric, perfect for daily wear and outings.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/shirt/1/c/b/m-10863018-roadster-original-imah6tdhk5nj8vnj.jpeg?q=70"
  },
  {
    "id": 12,
    "title": "Biba Women's Printed Kurti",
    "brand": "Biba",
    "category": "women",
    "price": 2599,
    "discountPercentage": 24,
    "discountedPrice": 1975,
    "stock": 38,
    "rating": 4.5,
    "description": "Elegant printed kurti crafted from soft rayon fabric, ideal for festive and casual occasions.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/kurta/h/d/z/-original-imahghesjh8yprnk.jpeg?q=70"
  },
  {
    "id": 13,
    "title": "Max Kids Cotton Shorts",
    "brand": "Max",
    "category": "kids",
    "price": 899,
    "discountPercentage": 15,
    "discountedPrice": 764,
    "stock": 72,
    "rating": 4.1,
    "description": "Comfortable cotton shorts for kids with elastic waistband and playful design.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/kids-short/1/k/x/8-9-years-s24fct20ablack-max-original-imagxngubywzmgw9.jpeg?q=70"
  },
  {
    "id": 14,
    "title": "Van Heusen Men's Formal Trousers",
    "brand": "Van Heusen",
    "category": "men",
    "price": 3299,
    "discountPercentage": 18,
    "discountedPrice": 2705,
    "stock": 34,
    "rating": 4.4,
    "description": "Premium slim-fit formal trousers designed for office and business wear with superior comfort.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/trouser/n/t/h/40-vhtffslb193498-van-heusen-original-imahjc29untqzgay.jpeg?q=70"
  },
  {
    "id": 15,
    "title": "Forever 21 Women's Skinny Jeans",
    "brand": "Forever 21",
    "category": "women",
    "price": 2799,
    "discountPercentage": 22,
    "discountedPrice": 2183,
    "stock": 41,
    "rating": 4.3,
    "description": "Stretchable skinny jeans with modern fit and stylish finish for everyday fashion.",
    "img": "https://rukminim2.flixcart.com/img/612/612/l432ikw0/jean/d/x/w/24-59668702-forever21-original-imagf2fzt8gcykdm.jpeg?q=70"
  },



  {
    "id": 16,
    "title": "Tommy Hilfiger Men's Polo T-Shirt",
    "brand": "Tommy Hilfiger",
    "category": "men",
    "price": 3499,
    "discountPercentage": 20,
    "discountedPrice": 2799,
    "stock": 36,
    "rating": 4.6,
    "description": "Classic polo t-shirt made with premium cotton fabric, featuring signature logo and comfortable fit.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/t-shirt/v/b/3/-original-imahggfggv9zhsqc.jpeg?q=70"
  },
  {
    "id": 17,
    "title": "W for Woman Printed Palazzo Pants",
    "brand": "W for Woman",
    "category": "women",
    "price": 2199,
    "discountPercentage": 23,
    "discountedPrice": 1693,
    "stock": 44,
    "rating": 4.3,
    "description": "Stylish printed palazzo pants with relaxed fit, perfect for casual and festive wear.",
    "img": "https://rukminim2.flixcart.com/img/612/612/jmwch3k0/trouser/p/x/r/s-17au60645-50141-w-original-imaf9pbzzyzgtrpg.jpeg?q=70"
  },
  {
    "id": 18,
    "title": "Mothercare Kids Winter Sweater",
    "brand": "Mothercare",
    "category": "kids",
    "price": 1599,
    "discountPercentage": 17,
    "discountedPrice": 1327,
    "stock": 52,
    "rating": 4.4,
    "description": "Soft and warm winter sweater designed for kids with comfortable fabric and cute patterns.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/sweater/0/c/k/18-24-months-bpam-gtwo-original-imahg54yvqrrgafq.jpeg?q=70"
  },
  {
    "id": 19,
    "title": "Jack & Jones Men's Slim Fit Jacket",
    "brand": "Jack & Jones",
    "category": "men",
    "price": 5999,
    "discountPercentage": 19,
    "discountedPrice": 4859,
    "stock": 27,
    "rating": 4.5,
    "description": "Trendy slim fit jacket crafted with durable fabric, ideal for winter and casual outings.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/jacket/c/o/u/3xl-no-117703903-jack-jones-original-imah8nxzq5xs5vst.jpeg?q=70"
  },
  {
    "id": 20,
    "title": "ONLY Women's Casual Crop Top",
    "brand": "ONLY",
    "category": "women",
    "price": 1499,
    "discountPercentage": 25,
    "discountedPrice": 1124,
    "stock": 58,
    "rating": 4.2,
    "description": "Stylish casual crop top made with soft stretchable fabric, perfect for daily fashion wear.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/top/p/c/h/xl-194452202-only-original-imaguhzgakwz9yva.jpeg?q=70"
  },



  {
    "id": 21,
    "title": "Peter England Men's Formal Blazer",
    "brand": "Peter England",
    "category": "men",
    "price": 6999,
    "discountPercentage": 18,
    "discountedPrice": 5739,
    "stock": 29,
    "rating": 4.4,
    "description": "Elegant formal blazer crafted with premium fabric, perfect for office meetings and special occasions.",
    "img": "https://rukminim2.flixcart.com/img/612/612/ku2zjww0/blazer/l/s/g/44-pibzwnsfr68004-peter-england-original-imag7aahnphb8n7g.jpeg?q=70"
  },
  {
    "id": 22,
    "title": "Global Desi Women's Ethnic Kurta Set",
    "brand": "Global Desi",
    "category": "women",
    "price": 3499,
    "discountPercentage": 22,
    "discountedPrice": 2729,
    "stock": 37,
    "rating": 4.5,
    "description": "Beautiful ethnic kurta set with printed design and comfortable fabric for festive wear.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/salwar-kurta-dupatta/n/d/2/s-jacquard-bushi-original-imahkrcfwfwasgvt.jpeg?q=70"
  },
  {
    "id": 23,
    "title": "Gini & Jony Kids Casual Jeans",
    "brand": "Gini & Jony",
    "category": "kids",
    "price": 1299,
    "discountPercentage": 15,
    "discountedPrice": 1104,
    "stock": 61,
    "rating": 4.2,
    "description": "Durable and comfortable casual jeans for kids with stretchable denim fabric.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/jean/d/q/j/15-16-years-121246527412-9207-gini-jony-original-imaggkgjzh8d8xtw.jpeg?q=70"
  },
  {
    "id": 24,
    "title": "U.S. Polo Assn. Men's Casual Hoodie",
    "brand": "U.S. Polo Assn.",
    "category": "men",
    "price": 3999,
    "discountPercentage": 20,
    "discountedPrice": 3199,
    "stock": 40,
    "rating": 4.3,
    "description": "Warm and stylish casual hoodie made with soft fleece fabric for everyday comfort.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/sweatshirt/h/c/f/s-udswssoe0313-u-s-polo-assn-denim-co-original-imahg9e9hvwnmyy6.jpeg?q=70"
  },
  {
    "id": 25,
    "title": "Vero Moda Women's Skinny Fit Trousers",
    "brand": "Vero Moda",
    "category": "women",
    "price": 2799,
    "discountPercentage": 19,
    "discountedPrice": 2267,
    "stock": 33,
    "rating": 4.4,
    "description": "Modern skinny fit trousers designed with stretchable material for office and casual styling.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/trouser/r/s/h/m-132879201-vero-moda-original-imagpneyn5zutwsf.jpeg?q=70"
  },


  {
    "id": 26,
    "title": "Louis Philippe Men's Slim Fit Shirt",
    "brand": "Louis Philippe",
    "category": "men",
    "price": 3299,
    "discountPercentage": 21,
    "discountedPrice": 2606,
    "stock": 38,
    "rating": 4.5,
    "description": "Premium slim fit formal shirt crafted with high-quality cotton fabric for a sharp and elegant look.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/shirt/g/f/h/m-tbh-andreas-mr-the-bear-house-original-imahcdymhksn2zye.jpeg?q=70"
  },
  {
    "id": 27,
    "title": "AND Women's Floral Maxi Dress",
    "brand": "AND",
    "category": "women",
    "price": 4599,
    "discountPercentage": 24,
    "discountedPrice": 3495,
    "stock": 26,
    "rating": 4.6,
    "description": "Elegant floral maxi dress made with lightweight fabric, perfect for parties and special occasions.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/dress/3/p/x/s-stylish-smocking-dress-bright-nex-original-imah8mqgnumfugxz.jpeg?q=70"
  },
  {
    "id": 28,
    "title": "Hopscotch Kids Printed Night Suit",
    "brand": "Hopscotch",
    "category": "kids",
    "price": 1199,
    "discountPercentage": 18,
    "discountedPrice": 983,
    "stock": 54,
    "rating": 4.3,
    "description": "Soft and comfortable printed night suit set designed for kids with breathable cotton fabric.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/kids-apparel-combo/l/3/8/3-4-years-cottonshirt1-emblica-original-imahfca9cgfas5sg.jpeg?q=70"
  },
  {
    "id": 29,
    "title": "Wrangler Men's Regular Fit Jeans",
    "brand": "Wrangler",
    "category": "men",
    "price": 3499,
    "discountPercentage": 20,
    "discountedPrice": 2799,
    "stock": 42,
    "rating": 4.4,
    "description": "Classic regular fit denim jeans with durable stitching and comfortable stretch fabric.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/jean/i/m/j/40-wmjn005349-wrangler-original-imagvgkjhz4pbhm2.jpeg?q=70"
  },
  {
    "id": 30,
    "title": "Fabindia Women's Cotton Kurta",
    "brand": "Fabindia",
    "category": "women",
    "price": 2999,
    "discountPercentage": 22,
    "discountedPrice": 2339,
    "stock": 31,
    "rating": 4.5,
    "description": "Traditional cotton kurta with elegant design and soft breathable fabric for everyday ethnic wear.",
    "img": "https://rukminim2.flixcart.com/img/612/612/xif0q/kurta/5/n/a/m-1043913indigo-fabindia-original-imahgzhamcr8jyke.jpeg?q=70"
  },




  {
    "id": 31,
    "title": "Allen Solly Men's Polo T-Shirt",
    "brand": "Allen Solly",
    "category": "men",
    "price": 2199,
    "discountPercentage": 25,
    "discountedPrice": 1649,
    "stock": 47,
    "rating": 4.3,
    "description": "Comfortable polo t-shirt made with breathable cotton fabric for casual everyday wear.",
    "img": "https://via.placeholder.com/300?text=Allen+Solly+Polo"
  },
  {
    "id": 32,
    "title": "Biba Women's Anarkali Kurti",
    "brand": "Biba",
    "category": "women",
    "price": 3999,
    "discountPercentage": 28,
    "discountedPrice": 2879,
    "stock": 34,
    "rating": 4.6,
    "description": "Graceful Anarkali kurti featuring elegant embroidery, perfect for festive occasions.",
    "img": "https://via.placeholder.com/300?text=Biba+Anarkali"
  },
  {
    "id": 33,
    "title": "Mothercare Kids Winter Jacket",
    "brand": "Mothercare",
    "category": "kids",
    "price": 2599,
    "discountPercentage": 20,
    "discountedPrice": 2079,
    "stock": 28,
    "rating": 4.4,
    "description": "Warm and cozy winter jacket designed for kids with soft inner lining and hood.",
    "img": "https://via.placeholder.com/300?text=Mothercare+Jacket"
  },
  {
    "id": 34,
    "title": "Levi's Men's Slim Fit Jeans",
    "brand": "Levi's",
    "category": "men",
    "price": 4299,
    "discountPercentage": 23,
    "discountedPrice": 3310,
    "stock": 36,
    "rating": 4.7,
    "description": "Premium slim fit denim jeans with durable stitching and modern styling.",
    "img": "https://via.placeholder.com/300?text=Levis+Slim+Jeans"
  },
  {
    "id": 35,
    "title": "ONLY Women's Casual Denim Jacket",
    "brand": "ONLY",
    "category": "women",
    "price": 3799,
    "discountPercentage": 26,
    "discountedPrice": 2811,
    "stock": 30,
    "rating": 4.5,
    "description": "Trendy denim jacket with classic button closure and comfortable stretch fabric.",
    "img": "https://via.placeholder.com/300?text=ONLY+Denim+Jacket"
  },


  {
    "id": 36,
    "title": "Van Heusen Men's Formal Trousers",
    "brand": "Van Heusen",
    "category": "men",
    "price": 2899,
    "discountPercentage": 19,
    "discountedPrice": 2348,
    "stock": 41,
    "rating": 4.4,
    "description": "Classic formal trousers designed with wrinkle-resistant fabric for a polished office look.",
    "img": "https://via.placeholder.com/300?text=Van+Heusen+Trousers"
  },
  {
    "id": 37,
    "title": "W for Woman Printed Straight Kurta",
    "brand": "W for Woman",
    "category": "women",
    "price": 2599,
    "discountPercentage": 27,
    "discountedPrice": 1897,
    "stock": 39,
    "rating": 4.5,
    "description": "Elegant printed straight kurta made with soft breathable fabric for daily ethnic styling.",
    "img": "https://via.placeholder.com/300?text=W+Kurta"
  },
  {
    "id": 38,
    "title": "Peppermint Kids Party Dress",
    "brand": "Peppermint",
    "category": "kids",
    "price": 1899,
    "discountPercentage": 22,
    "discountedPrice": 1481,
    "stock": 33,
    "rating": 4.3,
    "description": "Stylish party dress for kids featuring beautiful design and comfortable inner lining.",
    "img": "https://via.placeholder.com/300?text=Peppermint+Dress"
  },
  {
    "id": 39,
    "title": "HRX Men's Sports Track Pants",
    "brand": "HRX",
    "category": "men",
    "price": 2499,
    "discountPercentage": 24,
    "discountedPrice": 1899,
    "stock": 46,
    "rating": 4.4,
    "description": "Lightweight and stretchable sports track pants perfect for workouts and daily activities.",
    "img": "https://via.placeholder.com/300?text=HRX+Track+Pants"
  },
  {
    "id": 40,
    "title": "Zara Women's Oversized Sweater",
    "brand": "Zara",
    "category": "women",
    "price": 4599,
    "discountPercentage": 21,
    "discountedPrice": 3633,
    "stock": 27,
    "rating": 4.6,
    "description": "Trendy oversized sweater crafted with soft knit fabric for a cozy winter look.",
    "img": "https://via.placeholder.com/300?text=Zara+Sweater"
  },



  {
    "id": 41,
    "title": "Park Avenue Men's Formal Suit",
    "brand": "Park Avenue",
    "category": "men",
    "price": 8999,
    "discountPercentage": 20,
    "discountedPrice": 7199,
    "stock": 22,
    "rating": 4.6,
    "description": "Premium formal suit tailored with fine fabric for business meetings and special occasions.",
    "img": "https://via.placeholder.com/300?text=Park+Avenue+Suit"
  },
  {
    "id": 42,
    "title": "Sassafras Women's Crop Top",
    "brand": "Sassafras",
    "category": "women",
    "price": 1499,
    "discountPercentage": 30,
    "discountedPrice": 1049,
    "stock": 58,
    "rating": 4.2,
    "description": "Trendy crop top with modern fit and soft fabric, perfect for casual outings.",
    "img": "https://via.placeholder.com/300?text=Sassafras+Crop+Top"
  },
  {
    "id": 43,
    "title": "Mini Klub Kids Cotton T-Shirt",
    "brand": "Mini Klub",
    "category": "kids",
    "price": 799,
    "discountPercentage": 15,
    "discountedPrice": 679,
    "stock": 73,
    "rating": 4.3,
    "description": "Soft cotton t-shirt for kids with playful prints and comfortable fit.",
    "img": "https://via.placeholder.com/300?text=Mini+Klub+TShirt"
  },
  {
    "id": 44,
    "title": "Roadster Men's Checked Casual Shirt",
    "brand": "Roadster",
    "category": "men",
    "price": 1999,
    "discountPercentage": 25,
    "discountedPrice": 1499,
    "stock": 49,
    "rating": 4.4,
    "description": "Stylish checked casual shirt made with breathable cotton for everyday wear.",
    "img": "https://via.placeholder.com/300?text=Roadster+Shirt"
  },
  {
    "id": 45,
    "title": "H&M Women's Pleated Skirt",
    "brand": "H&M",
    "category": "women",
    "price": 2299,
    "discountPercentage": 22,
    "discountedPrice": 1793,
    "stock": 36,
    "rating": 4.5,
    "description": "Elegant pleated skirt designed with lightweight fabric for a chic and modern look.",
    "img": "https://via.placeholder.com/300?text=HM+Pleated+Skirt"
  },



  {
    "id": 46,
    "title": "Jack & Jones Men's Casual Jacket",
    "brand": "Jack & Jones",
    "category": "men",
    "price": 5499,
    "discountPercentage": 23,
    "discountedPrice": 4234,
    "stock": 25,
    "rating": 4.5,
    "description": "Stylish casual jacket with modern fit and premium fabric for winter fashion.",
    "img": "https://via.placeholder.com/300?text=Jack+Jones+Jacket"
  },
  {
    "id": 47,
    "title": "Forever 21 Women's Bodycon Dress",
    "brand": "Forever 21",
    "category": "women",
    "price": 2799,
    "discountPercentage": 28,
    "discountedPrice": 2015,
    "stock": 32,
    "rating": 4.4,
    "description": "Trendy bodycon dress crafted with stretchable material for party wear.",
    "img": "https://via.placeholder.com/300?text=Forever21+Dress"
  },
  {
    "id": 48,
    "title": "LilPicks Kids Denim Dungaree",
    "brand": "LilPicks",
    "category": "kids",
    "price": 1599,
    "discountPercentage": 20,
    "discountedPrice": 1279,
    "stock": 44,
    "rating": 4.3,
    "description": "Comfortable denim dungaree set designed for active kids.",
    "img": "https://via.placeholder.com/300?text=Kids+Dungaree"
  },
  {
    "id": 49,
    "title": "Tommy Hilfiger Men's Crew Neck T-Shirt",
    "brand": "Tommy Hilfiger",
    "category": "men",
    "price": 3499,
    "discountPercentage": 18,
    "discountedPrice": 2869,
    "stock": 38,
    "rating": 4.6,
    "description": "Premium crew neck t-shirt with signature branding and soft cotton fabric.",
    "img": "https://via.placeholder.com/300?text=Tommy+TShirt"
  },
  {
    "id": 50,
    "title": "Zudio Women's Casual Top",
    "brand": "Zudio",
    "category": "women",
    "price": 999,
    "discountPercentage": 15,
    "discountedPrice": 849,
    "stock": 60,
    "rating": 4.2,
    "description": "Lightweight casual top perfect for daily wear with comfortable fit.",
    "img": "https://via.placeholder.com/300?text=Zudio+Top"
  },
  {
    "id": 51,
    "title": "US Polo Kids Sports Shorts",
    "brand": "U.S. Polo Assn.",
    "category": "kids",
    "price": 899,
    "discountPercentage": 17,
    "discountedPrice": 746,
    "stock": 70,
    "rating": 4.3,
    "description": "Breathable sports shorts designed for active kids with elastic waistband.",
    "img": "https://via.placeholder.com/300?text=Kids+Shorts"
  },
  {
    "id": 52,
    "title": "Arrow Men's Formal Shirt",
    "brand": "Arrow",
    "category": "men",
    "price": 2999,
    "discountPercentage": 22,
    "discountedPrice": 2339,
    "stock": 41,
    "rating": 4.5,
    "description": "Elegant formal shirt with wrinkle-resistant fabric for office wear.",
    "img": "https://via.placeholder.com/300?text=Arrow+Shirt"
  },
  {
    "id": 53,
    "title": "Pantaloons Women's Palazzo Pants",
    "brand": "Pantaloons",
    "category": "women",
    "price": 1899,
    "discountPercentage": 24,
    "discountedPrice": 1443,
    "stock": 48,
    "rating": 4.4,
    "description": "Stylish palazzo pants with relaxed fit and soft breathable material.",
    "img": "https://via.placeholder.com/300?text=Palazzo+Pants"
  },
  {
    "id": 54,
    "title": "FirstCry Kids Winter Sweater",
    "brand": "FirstCry",
    "category": "kids",
    "price": 1399,
    "discountPercentage": 21,
    "discountedPrice": 1105,
    "stock": 52,
    "rating": 4.3,
    "description": "Warm knitted sweater for kids with comfortable soft inner lining.",
    "img": "https://via.placeholder.com/300?text=Kids+Sweater"
  },
  {
    "id": 55,
    "title": "Being Human Men's Graphic T-Shirt",
    "brand": "Being Human",
    "category": "men",
    "price": 2199,
    "discountPercentage": 20,
    "discountedPrice": 1759,
    "stock": 45,
    "rating": 4.5,
    "description": "Casual graphic t-shirt made with premium cotton for trendy street style.",
    "img": "https://via.placeholder.com/300?text=Being+Human+TShirt"
  },


  {
    "id": 56,
    "title": "Mufti Men's Slim Fit Casual Shirt",
    "brand": "Mufti",
    "category": "men",
    "price": 2799,
    "discountPercentage": 21,
    "discountedPrice": 2211,
    "stock": 34,
    "rating": 4.4,
    "description": "Slim fit casual shirt with modern styling and breathable cotton fabric.",
    "img": "https://via.placeholder.com/300?text=Mufti+Shirt"
  },
  {
    "id": 57,
    "title": "Libas Women's Embroidered Kurta",
    "brand": "Libas",
    "category": "women",
    "price": 2499,
    "discountPercentage": 26,
    "discountedPrice": 1849,
    "stock": 37,
    "rating": 4.5,
    "description": "Elegant embroidered kurta crafted with soft fabric for festive and daily wear.",
    "img": "https://via.placeholder.com/300?text=Libas+Kurta"
  },
  {
    "id": 58,
    "title": "Tiny Girl Kids Frock Dress",
    "brand": "Tiny Girl",
    "category": "kids",
    "price": 1299,
    "discountPercentage": 18,
    "discountedPrice": 1065,
    "stock": 55,
    "rating": 4.3,
    "description": "Cute and stylish frock dress designed with soft and comfortable material for kids.",
    "img": "https://via.placeholder.com/300?text=Kids+Frock"
  },
  {
    "id": 59,
    "title": "Flying Machine Men's Denim Jacket",
    "brand": "Flying Machine",
    "category": "men",
    "price": 4999,
    "discountPercentage": 24,
    "discountedPrice": 3799,
    "stock": 29,
    "rating": 4.6,
    "description": "Classic denim jacket with durable stitching and comfortable fit.",
    "img": "https://via.placeholder.com/300?text=Denim+Jacket"
  },
  {
    "id": 60,
    "title": "DressBerry Women's A-Line Dress",
    "brand": "DressBerry",
    "category": "women",
    "price": 1999,
    "discountPercentage": 22,
    "discountedPrice": 1559,
    "stock": 43,
    "rating": 4.4,
    "description": "Chic A-line dress with lightweight fabric for casual outings.",
    "img": "https://via.placeholder.com/300?text=ALine+Dress"
  },
  {
    "id": 61,
    "title": "Babyhug Kids Cotton Romper",
    "brand": "Babyhug",
    "category": "kids",
    "price": 899,
    "discountPercentage": 20,
    "discountedPrice": 719,
    "stock": 68,
    "rating": 4.2,
    "description": "Soft cotton romper designed for maximum comfort and flexibility.",
    "img": "https://via.placeholder.com/300?text=Kids+Romper"
  },
  {
    "id": 62,
    "title": "Blackberrys Men's Formal Blazer",
    "brand": "Blackberrys",
    "category": "men",
    "price": 7499,
    "discountPercentage": 19,
    "discountedPrice": 6074,
    "stock": 21,
    "rating": 4.6,
    "description": "Premium formal blazer tailored with high-quality fabric for elegant styling.",
    "img": "https://via.placeholder.com/300?text=Formal+Blazer"
  },
  {
    "id": 63,
    "title": "Aurelia Women's Printed Kurti",
    "brand": "Aurelia",
    "category": "women",
    "price": 1799,
    "discountPercentage": 25,
    "discountedPrice": 1349,
    "stock": 46,
    "rating": 4.5,
    "description": "Comfortable printed kurti ideal for daily ethnic wear.",
    "img": "https://via.placeholder.com/300?text=Printed+Kurti"
  },
  {
    "id": 64,
    "title": "United Colors of Benetton Kids Hoodie",
    "brand": "United Colors of Benetton",
    "category": "kids",
    "price": 1899,
    "discountPercentage": 23,
    "discountedPrice": 1462,
    "stock": 39,
    "rating": 4.4,
    "description": "Warm hoodie for kids with stylish design and soft fleece lining.",
    "img": "https://via.placeholder.com/300?text=Kids+Hoodie"
  },
  {
    "id": 65,
    "title": "Nike Men's Sports T-Shirt",
    "brand": "Nike",
    "category": "men",
    "price": 2499,
    "discountPercentage": 18,
    "discountedPrice": 2049,
    "stock": 50,
    "rating": 4.7,
    "description": "High-performance sports t-shirt with sweat-wicking technology.",
    "img": "https://via.placeholder.com/300?text=Nike+Sports+TShirt"
  },



  {
    "id": 66,
    "title": "Adidas Men's Training Shorts",
    "brand": "Adidas",
    "category": "men",
    "price": 2199,
    "discountPercentage": 20,
    "discountedPrice": 1759,
    "stock": 48,
    "rating": 4.6,
    "description": "Lightweight training shorts with moisture-wicking fabric for workouts.",
    "img": "https://via.placeholder.com/300?text=Adidas+Shorts"
  },
  {
    "id": 67,
    "title": "Global Republic Women's Casual Shirt",
    "brand": "Global Republic",
    "category": "women",
    "price": 1699,
    "discountPercentage": 24,
    "discountedPrice": 1291,
    "stock": 42,
    "rating": 4.3,
    "description": "Stylish casual shirt with relaxed fit and breathable material.",
    "img": "https://via.placeholder.com/300?text=Women+Casual+Shirt"
  },
  {
    "id": 68,
    "title": "KiddoPanti Kids Printed Shorts Set",
    "brand": "KiddoPanti",
    "category": "kids",
    "price": 1399,
    "discountPercentage": 18,
    "discountedPrice": 1147,
    "stock": 57,
    "rating": 4.4,
    "description": "Comfortable printed shorts set designed for playful kids.",
    "img": "https://via.placeholder.com/300?text=Kids+Shorts+Set"
  },
  {
    "id": 69,
    "title": "Reebok Men's Sports Jacket",
    "brand": "Reebok",
    "category": "men",
    "price": 4599,
    "discountPercentage": 22,
    "discountedPrice": 3587,
    "stock": 30,
    "rating": 4.5,
    "description": "Durable sports jacket with modern fit and zip closure.",
    "img": "https://via.placeholder.com/300?text=Reebok+Jacket"
  },
  {
    "id": 70,
    "title": "Tokyo Talkies Women's Denim Skirt",
    "brand": "Tokyo Talkies",
    "category": "women",
    "price": 1899,
    "discountPercentage": 26,
    "discountedPrice": 1405,
    "stock": 36,
    "rating": 4.4,
    "description": "Trendy denim skirt with stylish cut and comfortable fabric.",
    "img": "https://via.placeholder.com/300?text=Denim+Skirt"
  },
  {
    "id": 71,
    "title": "Cutiekins Kids Party Suit",
    "brand": "Cutiekins",
    "category": "kids",
    "price": 2299,
    "discountPercentage": 21,
    "discountedPrice": 1816,
    "stock": 33,
    "rating": 4.3,
    "description": "Elegant party suit set for kids with soft inner lining.",
    "img": "https://via.placeholder.com/300?text=Kids+Party+Suit"
  },
  {
    "id": 72,
    "title": "Puma Men's Track Jacket",
    "brand": "Puma",
    "category": "men",
    "price": 3999,
    "discountPercentage": 23,
    "discountedPrice": 3079,
    "stock": 44,
    "rating": 4.6,
    "description": "Comfortable track jacket with sporty design and breathable fabric.",
    "img": "https://via.placeholder.com/300?text=Puma+Track+Jacket"
  },
  {
    "id": 73,
    "title": "Only & Sons Women's Casual Hoodie",
    "brand": "Only & Sons",
    "category": "women",
    "price": 2799,
    "discountPercentage": 25,
    "discountedPrice": 2099,
    "stock": 28,
    "rating": 4.5,
    "description": "Warm and stylish hoodie perfect for winter outings.",
    "img": "https://via.placeholder.com/300?text=Women+Hoodie"
  },
  {
    "id": 74,
    "title": "Nauti Nati Kids Cotton Shirt",
    "brand": "Nauti Nati",
    "category": "kids",
    "price": 999,
    "discountPercentage": 19,
    "discountedPrice": 809,
    "stock": 61,
    "rating": 4.2,
    "description": "Soft cotton shirt with fun prints designed for kids.",
    "img": "https://via.placeholder.com/300?text=Kids+Cotton+Shirt"
  },
  {
    "id": 75,
    "title": "Superdry Men's Graphic Hoodie",
    "brand": "Superdry",
    "category": "men",
    "price": 5499,
    "discountPercentage": 20,
    "discountedPrice": 4399,
    "stock": 27,
    "rating": 4.7,
    "description": "Premium graphic hoodie crafted with thick fleece for extra warmth.",
    "img": "https://via.placeholder.com/300?text=Superdry+Hoodie"
  },




  {
    "id": 76,
    "title": "Calvin Klein Men's Slim Fit T-Shirt",
    "brand": "Calvin Klein",
    "category": "men",
    "price": 3999,
    "discountPercentage": 18,
    "discountedPrice": 3279,
    "stock": 35,
    "rating": 4.6,
    "description": "Premium slim fit t-shirt made with soft stretch cotton for a modern look.",
    "img": "https://via.placeholder.com/300?text=CK+TShirt"
  },
  {
    "id": 77,
    "title": "Anouk Women's Ethnic Gown",
    "brand": "Anouk",
    "category": "women",
    "price": 4599,
    "discountPercentage": 27,
    "discountedPrice": 3357,
    "stock": 29,
    "rating": 4.5,
    "description": "Beautiful ethnic gown with intricate prints and flowy fabric.",
    "img": "https://via.placeholder.com/300?text=Ethnic+Gown"
  },
  {
    "id": 78,
    "title": "Tales & Stories Kids Casual T-Shirt",
    "brand": "Tales & Stories",
    "category": "kids",
    "price": 799,
    "discountPercentage": 15,
    "discountedPrice": 679,
    "stock": 64,
    "rating": 4.3,
    "description": "Colorful printed t-shirt designed with breathable cotton fabric for kids.",
    "img": "https://via.placeholder.com/300?text=Kids+Casual+TShirt"
  },
  {
    "id": 79,
    "title": "Woodland Men's Outdoor Jacket",
    "brand": "Woodland",
    "category": "men",
    "price": 6999,
    "discountPercentage": 22,
    "discountedPrice": 5459,
    "stock": 23,
    "rating": 4.6,
    "description": "Rugged outdoor jacket built for durability and warmth.",
    "img": "https://via.placeholder.com/300?text=Outdoor+Jacket"
  },
  {
    "id": 80,
    "title": "Forever New Women's Midi Dress",
    "brand": "Forever New",
    "category": "women",
    "price": 3799,
    "discountPercentage": 24,
    "discountedPrice": 2887,
    "stock": 31,
    "rating": 4.5,
    "description": "Elegant midi dress crafted with lightweight fabric for special occasions.",
    "img": "https://via.placeholder.com/300?text=Midi+Dress"
  },
  {
    "id": 81,
    "title": "Little Kangaroos Kids Joggers",
    "brand": "Little Kangaroos",
    "category": "kids",
    "price": 1099,
    "discountPercentage": 20,
    "discountedPrice": 879,
    "stock": 52,
    "rating": 4.4,
    "description": "Comfortable joggers with elastic waistband for active kids.",
    "img": "https://via.placeholder.com/300?text=Kids+Joggers"
  },
  {
    "id": 82,
    "title": "Under Armour Men's Sports Tank",
    "brand": "Under Armour",
    "category": "men",
    "price": 2299,
    "discountPercentage": 19,
    "discountedPrice": 1862,
    "stock": 47,
    "rating": 4.6,
    "description": "Performance sports tank with sweat-wicking technology.",
    "img": "https://via.placeholder.com/300?text=Sports+Tank"
  },
  {
    "id": 83,
    "title": "Sera Women's Floral Top",
    "brand": "Sera",
    "category": "women",
    "price": 1499,
    "discountPercentage": 23,
    "discountedPrice": 1154,
    "stock": 40,
    "rating": 4.4,
    "description": "Trendy floral top with relaxed fit and soft material.",
    "img": "https://via.placeholder.com/300?text=Floral+Top"
  },
  {
    "id": 84,
    "title": "Babyoye Kids Winter Coat",
    "brand": "Babyoye",
    "category": "kids",
    "price": 2499,
    "discountPercentage": 21,
    "discountedPrice": 1974,
    "stock": 28,
    "rating": 4.3,
    "description": "Warm winter coat with hood and soft inner lining for kids.",
    "img": "https://via.placeholder.com/300?text=Kids+Winter+Coat"
  },
  {
    "id": 85,
    "title": "Guess Men's Printed Casual Shirt",
    "brand": "Guess",
    "category": "men",
    "price": 4599,
    "discountPercentage": 20,
    "discountedPrice": 3679,
    "stock": 26,
    "rating": 4.7,
    "description": "Premium printed casual shirt with stylish fit and smooth fabric.",
    "img": "https://via.placeholder.com/300?text=Printed+Casual+Shirt"
  },


  {
    "id": 86,
    "title": "Arrow Sport Men's Polo T-Shirt",
    "brand": "Arrow Sport",
    "category": "men",
    "price": 2399,
    "discountPercentage": 21,
    "discountedPrice": 1895,
    "stock": 39,
    "rating": 4.5,
    "description": "Classic polo t-shirt with breathable cotton fabric and comfortable fit.",
    "img": "https://via.placeholder.com/300?text=Arrow+Sport+Polo"
  },
  {
    "id": 87,
    "title": "Indya Women's Festive Lehenga Set",
    "brand": "Indya",
    "category": "women",
    "price": 7999,
    "discountPercentage": 25,
    "discountedPrice": 5999,
    "stock": 18,
    "rating": 4.6,
    "description": "Elegant festive lehenga set with detailed embroidery and premium fabric.",
    "img": "https://via.placeholder.com/300?text=Lehenga+Set"
  },
  {
    "id": 88,
    "title": "Fox Kids Casual Hoodie",
    "brand": "Fox",
    "category": "kids",
    "price": 1299,
    "discountPercentage": 20,
    "discountedPrice": 1039,
    "stock": 54,
    "rating": 4.3,
    "description": "Soft and warm casual hoodie for kids with modern design.",
    "img": "https://via.placeholder.com/300?text=Kids+Casual+Hoodie"
  },
  {
    "id": 89,
    "title": "Monte Carlo Men's Wool Sweater",
    "brand": "Monte Carlo",
    "category": "men",
    "price": 3599,
    "discountPercentage": 22,
    "discountedPrice": 2807,
    "stock": 31,
    "rating": 4.6,
    "description": "Warm wool sweater designed for winter comfort and elegant style.",
    "img": "https://via.placeholder.com/300?text=Wool+Sweater"
  },
  {
    "id": 90,
    "title": "Chemistry Women's Wrap Dress",
    "brand": "Chemistry",
    "category": "women",
    "price": 2699,
    "discountPercentage": 24,
    "discountedPrice": 2051,
    "stock": 36,
    "rating": 4.4,
    "description": "Stylish wrap dress with flattering fit and soft fabric.",
    "img": "https://via.placeholder.com/300?text=Wrap+Dress"
  },
  {
    "id": 91,
    "title": "UFO Kids Graphic T-Shirt",
    "brand": "UFO",
    "category": "kids",
    "price": 899,
    "discountPercentage": 18,
    "discountedPrice": 737,
    "stock": 63,
    "rating": 4.2,
    "description": "Fun graphic t-shirt with vibrant prints and comfortable cotton fabric.",
    "img": "https://via.placeholder.com/300?text=Graphic+TShirt"
  },
  {
    "id": 92,
    "title": "Peter England Men's Casual Trousers",
    "brand": "Peter England",
    "category": "men",
    "price": 2799,
    "discountPercentage": 20,
    "discountedPrice": 2239,
    "stock": 42,
    "rating": 4.5,
    "description": "Smart casual trousers suitable for office and daily wear.",
    "img": "https://via.placeholder.com/300?text=Casual+Trousers"
  },
  {
    "id": 93,
    "title": "Mast & Harbour Women's Checked Shirt",
    "brand": "Mast & Harbour",
    "category": "women",
    "price": 1799,
    "discountPercentage": 23,
    "discountedPrice": 1385,
    "stock": 40,
    "rating": 4.4,
    "description": "Trendy checked shirt with relaxed fit and soft fabric.",
    "img": "https://via.placeholder.com/300?text=Checked+Shirt"
  },
  {
    "id": 94,
    "title": "Cherry Crumble Kids Party Dress",
    "brand": "Cherry Crumble",
    "category": "kids",
    "price": 1899,
    "discountPercentage": 21,
    "discountedPrice": 1500,
    "stock": 34,
    "rating": 4.3,
    "description": "Stylish party dress for kids with elegant detailing.",
    "img": "https://via.placeholder.com/300?text=Kids+Party+Dress"
  },
  {
    "id": 95,
    "title": "Hollister Men's Casual Hoodie",
    "brand": "Hollister",
    "category": "men",
    "price": 4999,
    "discountPercentage": 19,
    "discountedPrice": 4049,
    "stock": 28,
    "rating": 4.7,
    "description": "Premium casual hoodie with soft fleece interior and modern design.",
    "img": "https://via.placeholder.com/300?text=Casual+Hoodie"
  },



  {
    "id": 96,
    "title": "Van Heusen Sport Men's Active T-Shirt",
    "brand": "Van Heusen Sport",
    "category": "men",
    "price": 1999,
    "discountPercentage": 20,
    "discountedPrice": 1599,
    "stock": 46,
    "rating": 4.5,
    "description": "Breathable active t-shirt designed for workouts and daily comfort.",
    "img": "https://via.placeholder.com/300?text=Active+TShirt"
  },
  {
    "id": 97,
    "title": "Berrylush Women's Ruffle Dress",
    "brand": "Berrylush",
    "category": "women",
    "price": 2499,
    "discountPercentage": 25,
    "discountedPrice": 1874,
    "stock": 38,
    "rating": 4.4,
    "description": "Stylish ruffle dress with soft fabric and elegant silhouette.",
    "img": "https://via.placeholder.com/300?text=Ruffle+Dress"
  },
  {
    "id": 98,
    "title": "ToffyHouse Kids Printed Pyjama Set",
    "brand": "ToffyHouse",
    "category": "kids",
    "price": 1199,
    "discountPercentage": 18,
    "discountedPrice": 983,
    "stock": 59,
    "rating": 4.3,
    "description": "Comfortable printed pyjama set made from soft cotton for kids.",
    "img": "https://via.placeholder.com/300?text=Pyjama+Set"
  },
  {
    "id": 99,
    "title": "Levi's Men's Regular Fit Shirt",
    "brand": "Levi's",
    "category": "men",
    "price": 3499,
    "discountPercentage": 22,
    "discountedPrice": 2729,
    "stock": 33,
    "rating": 4.6,
    "description": "Classic regular fit shirt with durable stitching and premium finish.",
    "img": "https://via.placeholder.com/300?text=Regular+Fit+Shirt"
  },
  {
    "id": 100,
    "title": "Vishudh Women's Printed Saree",
    "brand": "Vishudh",
    "category": "women",
    "price": 2999,
    "discountPercentage": 24,
    "discountedPrice": 2279,
    "stock": 26,
    "rating": 4.5,
    "description": "Elegant printed saree crafted with lightweight and graceful fabric.",
    "img": "https://via.placeholder.com/300?text=Printed+Saree"
  },
  {
    "id": 101,
    "title": "Little Muffet Kids Cotton Shorts",
    "brand": "Little Muffet",
    "category": "kids",
    "price": 899,
    "discountPercentage": 17,
    "discountedPrice": 746,
    "stock": 67,
    "rating": 4.2,
    "description": "Soft cotton shorts designed for maximum comfort and flexibility.",
    "img": "https://via.placeholder.com/300?text=Cotton+Shorts"
  },
  {
    "id": 102,
    "title": "Arrow New York Men's Formal Suit",
    "brand": "Arrow New York",
    "category": "men",
    "price": 9999,
    "discountPercentage": 20,
    "discountedPrice": 7999,
    "stock": 19,
    "rating": 4.7,
    "description": "Premium formal suit tailored for sharp business and event styling.",
    "img": "https://via.placeholder.com/300?text=Formal+Suit"
  },
  {
    "id": 103,
    "title": "Aarika Women's Embellished Kurta",
    "brand": "Aarika",
    "category": "women",
    "price": 1899,
    "discountPercentage": 23,
    "discountedPrice": 1462,
    "stock": 41,
    "rating": 4.4,
    "description": "Beautiful embellished kurta ideal for festive and casual wear.",
    "img": "https://via.placeholder.com/300?text=Embellished+Kurta"
  },
  {
    "id": 104,
    "title": "Kidling Kids Winter Tracksuit",
    "brand": "Kidling",
    "category": "kids",
    "price": 1599,
    "discountPercentage": 21,
    "discountedPrice": 1263,
    "stock": 45,
    "rating": 4.3,
    "description": "Warm winter tracksuit set perfect for outdoor activities.",
    "img": "https://via.placeholder.com/300?text=Winter+Tracksuit"
  },
  {
    "id": 105,
    "title": "US Polo Assn. Men's Casual Sweatshirt",
    "brand": "U.S. Polo Assn.",
    "category": "men",
    "price": 3299,
    "discountPercentage": 19,
    "discountedPrice": 2672,
    "stock": 37,
    "rating": 4.6,
    "description": "Comfortable casual sweatshirt with soft inner lining and modern fit.",
    "img": "https://via.placeholder.com/300?text=Casual+Sweatshirt"
  }
];

app.get("/products", (req, res) => {

  const page = parseInt(req.query._page) || 1;
  const limit = parseInt(req.query._limit) || products.length;

  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;

  const paginatedProducts = products.slice(startIndex, endIndex);

  res.set("X-Total-Count", products.length); // pagination header
  res.json(paginatedProducts);
});

const PORT = 5000;

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});